name: attributed_text
description: Text with metadata spans for easy text editing and styling.
version: 0.2.0
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.2.0
  collection: ^1.15.0
  logging: ^1.0.1
  meta: ^1.7.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.0
  json_serializable: ^6.3.1